### ISSUE TITLE
Add a list of search provider options {streamsnooper.com}

### ISSUE THREAD

**Issue by collest** [fuomag9/Periscope-Recorder-Gui#1]
It is the first time I deal with C # and I do not have many ideas on how to change your application, especially in changing the live search provider http://liveomg.com/?sort=rising by https://streamsnooper.com/all-rising-20-periscope-livestreams-page-1.html.

`public override void Init()
        {
            this.Request("https://streamsnooper.com/all-rising-20-periscope-livestreams-page-1.html", Parse);
        }`
I get the following error:
![error](https://user-images.githubusercontent.com/45525494/57266783-1f31fc00-7043-11e9-9c0c-99b26ea2d916.png)

The problem is that streamsnooper.com generates a link with its own shortener.

Example:

https://streamsnooper.com/zld3b039ecd49ccd8b00835197e4850f73 generates the following
 https://www.pscp.tv/w/1MnxnvbpzPNxO

**Comment by fuomag9** [comment]
I haven't looked the issue up yet, but I believe it's due to the fact that
I hardcodened the scraper instead of searching by elements/classes ids. You
probably need to check what the response from the website is and adapt the
hard coding to it in order to find the links.

If you can't manage to do it I'll look it up later today and add an option
to select this provider

Ps: the shortened link (pscp.tv) shouldn't be a problem as the Regex
expression I've used should work correctly with them and process them as
normal links.

Il giorno mar 7 mag 2019 alle 04:13 collest <notifications@github.com> ha
scritto:

**Comment by fuomag9** [comment]
I think it's the website's fault for having a certificate that fails to check. (using wget fails to download the website unless disabling certificate checking)

I'll try to reimplement the code using another library(I planned to do that anyway as ironwebscraper sucks) and I'll report you back

**Comment by collest** [comment]
Thanks for your reply. Although ironwebscraper as I see it is the only one to make Web Scraping in c #

**Comment by fuomag9** [comment]
I'm working to implement it using
https://html-agility-pack.net, it should be ready in a few hours or so :)

**Comment by fuomag9** [comment]
Unfortunately I can't manage to get streamsnooper to work as it doesn't like me to scrape it and doesn't return the periscope links I'd expect (I believe it's an issue due to headers or stuff like that). 

Nonetheless I've modified the code heavily and implemented a list of websites(actually containing only liveomg for now) on 36675a894cb739d41a4734172b1f797338366709
